### ISSUE TITLE
您好，我想问一个问题？

### ISSUE THREAD

**Issue by Lweiwen** [JerryTZF/hyperf-v3#1]
您好， 我想问下如果是想中间件传参，应该如何处理呀，我有个需求就是每个路由api需要的场景判断不一样

**Comment by JerryTZF** [comment]
中间件中有请求对象，可以将你要传递的参数传递至该请求对象，但是要注意协程上下文，可以参考我的JwtMiddleware这个中间件发自我的 iPhone在 2023年12月11日，17:27，lww ***@***.***> 写道：﻿
您好， 我想问下如果是想中间件传参，应该如何处理呀，我有个需求就是每个路由api需要的场景判断不一样

**Comment by Lweiwen** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您发的邮件我已收到，尽快给你回复。

**Comment by Lweiwen** [comment]
你好，我是想问有没有可以类似laravel中间件那种操作，中间件传参，或者类似可以实现你方法，我的需求是这样子的：jwt中间件可以验证来着 pc端或者web端的token，但是比如api/upload：就是pc端或者web端token可以通过，api/user：就是只有web端token可以通过，api/pc：就是只有pc端token可以通过，依次类推。

**Comment by Lweiwen** [comment]
或者你可以留下你的联系方式吗，我想详细咨询一下，我是初学者，帮帮忙！

**Comment by JerryTZF** [comment]
发你的联系方式我加你吧

**Comment by JerryTZF** [comment]
发你的吧，我加你
















在 2023-12-12 10:51:37，"lww" ***@***.***> 写道：

或者你可以留下你的联系方式吗，我想详细咨询一下，我是初学者，帮帮忙！

**Comment by Lweiwen** [comment]
微信：781115101
